### ISSUE TITLE
timeouts

### ISSUE THREAD

**Issue by jordic** [zopefoundation/ZServer#2]
Is possible to set up any kind of request timeout? 
Trying to figure how. Not sure If I should ask this here or in other place.

**Comment by tseaver** [comment]
For clarification, are you asking about a "defend against broken / malicious clients" timeout, or "defend against broken application code" timeout?

In either case, the most expedient route would be to run Zope as a WSGI app, rather than via ZServer, and use a WSGI server which provides those features.  ZServer doesn't have support for either kind of timeout, and almost certainly won't grow any:  development on the project is no longer active.

**Comment by jordic** [comment]
Yup, I have a LB before and this has his own timeouts.. but I just want to have some kind of timeouts for internal (async tasks, called directly). (Mostly to defend agains poor app code) 

Anyway, many thanks. 
It's clear that the next steps will be to evolve our codebase to a wsgi deployment and run them with gunicorn or uwsgi :octopus:
